"""Initial database schema

Revision ID: ad6ef1a431a2
Revises: 
Create Date: 2026-09-24 20:57:45.728666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6ef1a431a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_user_id'), ['user_id'], unique=False)

    op.create_table('signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature')
    )
    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signatures_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signatures_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_signatures_user_id'), ['user_id'], unique=False)

    op.create_table('verification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature_id', sa.Integer(), nullable=False),
    sa.Column('verifier_id', sa.Integer(), nullable=True),
    sa.Column('verification_result', sa.Boolean(), nullable=False),
    sa.Column('verifier_ip', sa.String(length=45), nullable=True),
    sa.Column('verifier_agent', sa.Text(), nullable=True),
    sa.Column('verification_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signature_id'], ['signatures.id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_logs_signature_id'), ['signature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_logs_verifier_id'), ['verifier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_logs_verifier_id'))
        batch_op.drop_index(batch_op.f('ix_verification_logs_signature_id'))

    op.drop_table('verification_logs')
    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signatures_user_id'))
        batch_op.drop_index(batch_op.f('ix_signatures_status'))
        batch_op.drop_index(batch_op.f('ix_signatures_file_id'))

    op.drop_table('signatures')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_files_file_hash'))

    op.drop_table('files')
    op.drop_table('users')
    # ### end Alembic commands ###
